### ISSUE TITLE
Information for character counter

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate_mobile#112]
Proposal for the new version of the application to add information for the character counter. After clicking on the character counter, information about the number of characters would appear, for example: "Entered 15 characters out of 5000 possible".
If it exceeds the value of 5000 characters when the counter is red, then after tapping it may change to e.g. "Exceeded limit 5 characters out of 5000 possible".

Information like this: "The translation input is above 5000".

Such additional information would immediately explain what this meter is about. Currently, the user can click on the character counter, but nothing happens. Only later realizes that this is just information, not a function button.

**Comment by ManeraKai** [comment]
Fixed that.

**Comment by Valdnet** [comment]
A test version, please 😉.

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1313043971

**Comment by ManeraKai** [comment]
So you want the message to just appear once and never again?

**Comment by Valdnet** [comment]
Should be corrected:
No message appears when you enter text for the first time after deleting 1 character and re-entering the character. It appears only after deleting 2 characters and re-entering the character.

This **only** happens the first time you enter the text and after translating and deleting the text.

Current behavior example:
5010 (message appears) - **1** + 1 (**there is no message**, but it should appear) + 1 + 1
5010 (message appears) - **2** + 1 (message appears) + 1 + 1
5010 (message appears) - 1 + 1 (message appears) + 1 + 1

An example of correct operation:
5010 (message appears) - 1 + 1 (message appears) + 1 + 1
5010 (message appears) - 2 + 1 (message appears) + 1 + 1

**Comment by ManeraKai** [comment]
Fixed that: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1315058780

**Comment by ManeraKai** [comment]
I did that intentionally to make it as every other button:
<div>
<img width=360 src="https://user-images.githubusercontent.com/40805353/136353933-2c0484b6-ea87-4886-8a89-10d8a3779111.png"/>
<img width=360 src="https://user-images.githubusercontent.com/40805353/136353952-f58328c4-b0e2-4bb4-b46f-e89e67163bad.png"/>
</div>
Which one?

**Comment by Valdnet** [comment]
The character counter icon is now in the right place after adding information. It works as a button, only when you tap on the icon, the background of the icon is too large compared to the icon. I know you have a color problem on your monitor and you may not be able to see it. See it again:

![obraz](https://user-images.githubusercontent.com/47037905/136353565-b24dbf9c-3a9c-469f-a033-01cd1b8bcb4d.png)

😁

**Comment by ManeraKai** [comment]
Fixed it, but I'll push the commit with the translation. Btw, I'm trying to add variables to translation strings, but didn't find a documentation for that. Trying to find it.

**Comment by ManeraKai** [comment]
I'll add the Arabic translation with your @Valdnet  merge request. Don't merge it too quickly.

**Comment by ManeraKai** [comment]
Do you want to simplify variable names or add a percent sign instead of `$` to declare a variable?

**Comment by Valdnet** [comment]
I want the variables to be replaced with a `%` or `$` sign in the translation. No matter how easier it is for you. In dependencies, as the code allows 😉.

**Comment by ManeraKai** [comment]
`"input_calc": "Exceeded 5000 character limit by %lengthDifference",`
`"input_fraction": "Entered %length characters out of 5000 possible",` ?

**Comment by Valdnet** [comment]
> When you should say it's many? After 10?
There is a lot already at 5, that is: `5 characters`.

**Comment by Valdnet** [comment]
Translation made in PR: #119.

**Comment by Valdnet** [comment]
For a light theme, the character count icon should now be green (theme color). It now looks like it is inactive.

**Comment by ManeraKai** [comment]
<img width=360 src="https://user-images.githubusercontent.com/40805353/136507618-8ff2e961-8762-4d93-b554-b700b4b970b9.png"/>
?

**Comment by Valdnet** [comment]
Cool 👍. I close the issue.
