### ISSUE TITLE
Share list

### ISSUE THREAD

**Issue by mbnoimi** [ManeraKai/simplytranslate_mobile#125]
I suggest to add it into share list just like Google Translate do.

![image](https://user-images.githubusercontent.com/284547/136649163-848f0991-5d83-4d89-b082-00a763c97aa8.png)

**Comment by ManeraKai** [comment]
Try it: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1323546621

**Comment by mbnoimi** [comment]
> Try it: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1323546621

Works fine. 
Thanks

**Comment by Valdnet** [comment]
> More details?

I have translated the text "Testing" directly in the application. Then I closed the application. I opened a web browser. Then the text shares for the application.

I got an error that was constant all the time. Only removing the application memory allowed me to continue using it.

I was able to get the error once.

**Comment by ManeraKai** [comment]
Maybe caching issues as you've mentioned. I tried to reproduce it, but failed miserably.

**Comment by ManeraKai** [comment]
For now it seems there's no bugs. If anyone finds anything, either request opening this issue or open a new one. This issue will be closed for now.
