### ISSUE TITLE
Instance change to "Custom"

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate_mobile#128]
Steps:

1. Select application settings.
2. Select "Instances".
3. Choose "Custom".
4. Do not provide the address of the instance.
5. Cancel your selection.

The application should return to the previous instance setting if no instance is given. Currently, the user selection is not canceled (it only cancels the address window) and there is no text in the selection menu description.

![obraz](https://user-images.githubusercontent.com/47037905/136693807-dfc8538e-65a4-4c54-9a64-4730565bffda.png)

**Comment by ManeraKai** [comment]
Now Even the url will revert back: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1326409134

**Comment by Valdnet** [comment]
Works properly 👍. I close the issue.
