### ISSUE TITLE
Smartphone rotation

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate_mobile#130]
Steps:

1. Launch the application.
2. Tap on the text edit window (keyboard pop out).
3. Rotate the smartphone to a horizontal position.
4. Rotate the smartphone to an vertical position.

The application window is shifted up. The windows for changing languages are not visible.

![obraz](https://user-images.githubusercontent.com/47037905/136765956-e9b2db7e-fd1c-4807-9109-6d4c7b2ce203.png)

The application window should return to its previous state. To change the language of the translations, the user has to move them down.

**Comment by ManeraKai** [comment]
Reverted it.
