### ISSUE TITLE
UI in wrong language

### ISSUE THREAD

**Issue by maemunman** [ManeraKai/simplytranslate_mobile#131]
I have my phone in persian language, so when I opened simplytranslate, it automatically put UI in arabic.  I went to settings, and I think I changed the proper setting to persian "الفارسیه", but the UI is still in arabic despite that.

**Comment by ManeraKai** [comment]
Now if it finds a translation specific to a country e.g `en-US`, it will use it. Else if it finds just the language translation without country support e.g: `en`, it will use it. Else if it didn't find neither the country code nor the language code, it will go to the next language in the system, e.g `[ar, en]`. Else if it didn't find neither the contry nor the language code in any of the system's language list, it will fallback to `en`.

**Comment by ManeraKai** [comment]
Yeah why not.
