### ISSUE TITLE
Replace POEditor with Weblate for translations

### ISSUE THREAD

**Issue by ghost** [ManeraKai/simplytranslate_mobile#142]
It would be good if you do that. [Weblate](https://weblate.org) is free for FOSS projects, it doesn't spy on you (POEditor is full of trackers), Weblate is FOSS itself (unlike POEditor), and people can suggest translations without an account (unlike POEditor) which could provide you more languages.

**Comment by ManeraKai** [comment]
You have a really good point.

> The project has had active development for at least three months.

but that requirement, it will take time from us to switch.

And GitHub itself is another story.

**Comment by Valdnet** [comment]
Additionally, POEditor has no translation suggestions made by other translators for a similar text string.

Overall, I use a lot for translating [Transifex](https://transifex.com) as Coordinator, Reviewer and Translator and in my opinion it is good. You can approve translations, add your suggestion, comment and issue an issue. It's also free for open source projects and more professional.

**Comment by ManeraKai** [comment]
@Valdnet we'll discuss that after about 2 months when I meat the 3-month requirement on weblate.

**Comment by ManeraKai** [comment]
Some comments in this PR have opinions on POEditor: #156

**Comment by Aga-C** [comment]
@ManeraKai I've noticed that the project is already on Weblate, and there is a change in the English string. It's not yet here, so I'm wondering if it's OK for you, and can we apply this change in other languages?
Also, if you don't like having changed English strings, you can set language there as read-only.

**Comment by ManeraKai** [comment]
I'm setting it up for review. But I got a little busy with [OCR](https://en.wikipedia.org/wiki/Optical_character_recognition). I will see what happened with those English strings. I may reset everything.

**Comment by ManeraKai** [comment]
@Aga-C I've sent the request for approval to Weblate. Let's see how it'll go.

**Comment by ManeraKai** [comment]
@Aga-C @Valdnet @ghost, Weblate has approved simplytranslate_mobile 🎉

**Comment by ManeraKai** [comment]
@Valdnet Do you have comment on what happened with this change before closing the issue?

**Comment by Valdnet** [comment]
In my opinion, it translates better to me in POEdit. But Weblate might be functionally better 😉 .

**Comment by ManeraKai** [comment]
Weblate is opensource too. Makes more sense for this app's idea.
Yes, Weblate is a little bit complex or advanced.
