### ISSUE TITLE
from GNU General Public License v3.0 to GNU Affero General Public License v3.0

### ISSUE THREAD

**Issue by ManeraKai** [ManeraKai/simplytranslate_mobile#152]
@Valdnet @Aga-C @CafeTango @K3XRad @sunilpaulmathew @alefvanoon @metalune1

**Comment by K3XRad** [comment]
I give my consent to use my translation in this project under any license and even take away my authorship if my GitHub account will be deleted.

**Comment by Valdnet** [comment]
The GNU Affero General Public License relates more to web applications that run on the server. After all, the SimplyTranslate Mobile application is not a web application. Works as a client.

**Comment by ManeraKai** [comment]
> The GNU Affero General Public License relates more to web applications that run on the server. After all, the SimplyTranslate Mobile application is not a web application. Works as a client.

I though GPL allows making proprietary software out of the source code. Turns out the opposite. I think you're right @Valdnet. AGPl adds additional triggers for just online services.

**Comment by ManeraKai** [comment]
Will not change the license. We'll stay on GPL
