### ISSUE TITLE
Use system language as a default for translations

### ISSUE THREAD

**Issue by Aga-C** [ManeraKai/simplytranslate_mobile#153]
Hi,

I think that a useful improvement of the app would be to use system language as a default one for:
- translation language in sharing
- target language

It will be more user-friendly, since probably most use-cases will be translating from "auto-detect" to mother tongue of a user. Now by default in both cases is Arabic.

**Comment by Valdnet** [comment]
@Aga-C  Very good idea :+1:. I also believe that it will make it easier for the user to use the application.

Maybe ManeraKai wants to promote their language (joke) :grin:.

**Comment by ManeraKai** [comment]
I will take some time on this as I want to make the language values that are now `Arabic`, `Spanish` as `ar`, `es`

**Comment by ManeraKai** [comment]
Did it in this commit: https://github.com/ManeraKai/simplytranslate_mobile/commit/e388b13d86369c91e661d6413ddd6ccd4145c047
I should to fix some translations issues before I'm able to compile an `.apk`, it's giving me errors now.

**Comment by ManeraKai** [comment]
Fixed those errors in: https://github.com/ManeraKai/simplytranslate_mobile/commit/ed0c23965cee48590b0f2d932543d28f7eff06ec
`.apk`: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1429116641

**Comment by Aga-C** [comment]
I've tested on a device and on an emulator - translation doesn't work at all 🙁

**Comment by ManeraKai** [comment]
This is just temporarily. It should be `POST`.

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1429195278

**Comment by Aga-C** [comment]
Now it works ok.
BTW. There is an unrelated issue - all 3 language lists are not sorted alphabetically.

**Comment by ManeraKai** [comment]
Hopefully: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1429231236

**Comment by Aga-C** [comment]
Works great, thanks 👍

**Comment by Valdnet** [comment]
After this change, it is possible to select "Autodetect" for the language to which the text is to be translated. This selection should not appear for this window.

Additionally, when selecting "Autodetect" for the source language, change the `<- ->` button to inactive, because you cannot change the languages ​​between, for example: "Autodetect" `<- ->` "Polish".

**Comment by Aga-C** [comment]
> After this change, it is possible to select "Autodetect" for the language to which the text is to be translated.

And it's also visible in selecting language for share.

**Comment by Valdnet** [comment]
1. Also the language for shares that is automatically detected is gray. After changing to a different language and selecting your language again, you cannot select it.

![IMG_20211106_224851](https://user-images.githubusercontent.com/47037905/140624810-64bd4784-bf38-4d33-af69-88c85165160f.png)

2. After selecting the language, the window does not close automatically as it was before.

**Comment by ManeraKai** [comment]
About the autodetect. It really is weird . It's treating passed variables as pointers.
```
fromSelLangMap = toSelLangMap;
fromSelLangMap['auto'] = AppLocalizations.of(context)!.autodetect;
```
Apparently this changes both `fromSelLangMap` and `toSelLangMap`, treating `toSelLangMap` as a pointer rather than a value.

I fixed it btw.

**Comment by ManeraKai** [comment]
Forgot to mention this commit https://github.com/ManeraKai/simplytranslate_mobile/commit/9249337e9e1bb38f2067c283ddf150f24e1dff45
Fixed: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1430159688

**Comment by Valdnet** [comment]
1. The `<-->` language swap button does not change languages, but translates the text.

2. You can type and set different characters for the language.

![IMG_20211107_023348](https://user-images.githubusercontent.com/47037905/140628928-d1b6cc62-0176-4b6e-84a1-a737fba1e9eb.png)

Maybe it is left so that you can set your own unofficial language (joke) 😁.

**Comment by ManeraKai** [comment]
Fixed: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1431163568

**Comment by Valdnet** [comment]
Works correctly 👍.
