### ISSUE TITLE
[Feature request] Display alternative translations

### ISSUE THREAD

**Issue by TSnatch72** [ManeraKai/simplytranslate_mobile#154]
A very useful feature Google Translate has is that it shows you alternative translations (couples by their own alternative translations) ordered by frequency. Since Simply gathers the translations from google translate, it should be possible to also gather these. I believe adding this layout to the main screen would be a great QOL feature

Maybe even copying g translate's layout would work well

**Comment by ManeraKai** [comment]
The SimplyTranslate server app fetches data from: https://translate.google.com/m. That link doesn't include alternative words. This issue should be addressed though @metalune1

**Comment by TSnatch72** [comment]
I use a translation software on my pc that does a similar thing to simply called crow. It's able to show alternative words from various translators other than google like bing and yandex. Maybe its code and implementation of can give us the answer to this issue. You guys should give it a check

**Comment by ManeraKai** [comment]
Sorry for being late. Many things happening IRL. Anyway, I was trying to push a PR for the server application to find this comment:
![image](https://user-images.githubusercontent.com/40805353/148651618-0a041214-f15c-4498-8f09-915b5fc29ed3.png)

**Comment by ManeraKai** [comment]
This was the way that is in the desktop app that you use. It may be suitable for a client app, but not for servers that handle so much traffic.

**Comment by ManeraKai** [comment]
I think this may require scrapping the information from the webpage.

**Comment by TSnatch72** [comment]
So is it doable?

**Comment by ManeraKai** [comment]
I think that is what the Newpipe and invidious team did with youtube. Faking a videoplayer as I heard.
Yes, Doable. We'll try.

**Comment by TSnatch72** [comment]
Sweet!!! Godspeed with the project and keep up with the good work!

**Comment by ManeraKai** [comment]
For some updates, I was able to produce this: https://gist.github.com/ManeraKai/319e0fdc5583d90b018aea1115d8bdff

**Comment by ManeraKai** [comment]
Yesterday, I sent a two patches to SimplyTranslate:
https://lists.sr.ht/~metalune/simplytranslate-devel/%3CVI1P193MB04933897904C83FA48E2E33ADF5F9%40VI1P193MB0493.EURP193.PROD.OUTLOOK.COM%3E
https://lists.sr.ht/~metalune/simplytranslate-devel/patches/28730
And waiting

**Comment by ManeraKai** [comment]
@Valdnet @Aga-C This is how it looks, only use the Dark theme as I didn't optimize the colors for the White theme yet.

**Comment by ManeraKai** [comment]
If you were a little bit confused of where did I get those colors from, well they're the same colors that I've chosen for the main "web" version of SimplyTranslate https://simplytranslate.org/. Do they look good and contrasty on Android too?

**Comment by ManeraKai** [comment]
Forgot about the binary 😅: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2187138545

**Comment by Aga-C** [comment]
I always use Dark theme where it is possible, so for me this colors looks very good 👍
The only thing is missing space between Noun and Verb in Translations:
![image](https://user-images.githubusercontent.com/85929121/163944911-13a54097-8032-4003-abd8-3b8346248537.png)

**Comment by ManeraKai** [comment]
I've been refining it and added white theme support. Took your note an here's how it looks: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2188095808

**Comment by Aga-C** [comment]
Space is now ok, but why you've changed colors? They are less visible now on dark theme. Also, in definitions there is less information than it was before (see the screenshot below and compare it to the previous one).

![image](https://user-images.githubusercontent.com/85929121/163951446-e707179c-9112-4927-bbdd-3f4d70e856b4.png)

**Comment by ManeraKai** [comment]
oops!

The definitions have the same information but in a more elegant way.

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2188308074

**Comment by Aga-C** [comment]
> The definitions have the same information but in a more elegant way.

There is less info, you aren't showing synonyms.

App:
![image](https://user-images.githubusercontent.com/85929121/163958671-d7115050-1850-4c56-944f-6f5c40125abb.png)

Website:
![image](https://user-images.githubusercontent.com/85929121/163958841-d85ca1b0-491d-4f13-82f3-0edfce0c2699.png)

**Comment by ManeraKai** [comment]
oh sorry I thought you were talking about translations. will change it.

**Comment by ManeraKai** [comment]
Turns out It was just a misplacement of an `if` statement https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2189896605

**Comment by Aga-C** [comment]
Looks fine 🙂

**Comment by Valdnet** [comment]
@ManeraKai Very good job 👍. It looks nice and professional. Only issue #196 needs to be corrected.

**Comment by Aga-C** [comment]
@Valdnet For me, it doesn't matter.

**Comment by ManeraKai** [comment]
It's like this in GoogleTranslate:
![image](https://user-images.githubusercontent.com/40805353/164171637-3e78e83c-9f15-4095-816d-bed41016075f.png)
There's is a numbering scheme

**Comment by ManeraKai** [comment]
oh worry wrong issue with the commit.

**Comment by ManeraKai** [comment]
btw the copy button is working fine: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2228558244

I will add the translation strings later as I want to release a new version soon.

**Comment by Valdnet** [comment]
For a window with translated text, when it is empty:

1. "Zoom" and "TTS" buttons active.
2. After tapping the "Zoom" button an error appears.

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2229095138

**Comment by Valdnet** [comment]
@ManeraKai Display alternative translations does not work. Is this due to an application error? Is it a maladjustment of web applications to the new function?

**Comment by Valdnet** [comment]
Everything works correctly :+1:. Before a new version is released, in my opinion new translations should be downloaded.

**Comment by ManeraKai** [comment]
you mean from weblate?

**Comment by Valdnet** [comment]
Yes :wink:.

**Comment by ManeraKai** [comment]
I already did that before some days. They're up-to-date right now.

**Comment by Valdnet** [comment]
What about translations for "Customize Buttons" settings and other new text strings? Are they exported to Weblate?

**Comment by ManeraKai** [comment]
I'll do but after the release. Can you open a new issue for the release @Valdnet?

**Comment by Aga-C** [comment]
@ManeraKai Please wait for translations, or if you need to do this right now, at least release the app more often, so people can have strings translated.

**Comment by ManeraKai** [comment]
This time I want it fast as there's an incompatibility problem with almost all the instances.

**Comment by Valdnet** [comment]
Add text strings to Weblate and we will translate at least quickly into Polish to see if all the strings are correctly implemented in the code before the release.
Remember to download your translations before release.

@Aga-C will you translate?

**Comment by Aga-C** [comment]
> @Aga-C will you translate?

Yes.

**Comment by Valdnet** [comment]
> Can you open a new issue for the release @Valdnet?

Created 😉.

**Comment by ManeraKai** [comment]
I'll close this issue and add translation support in #199.
