### ISSUE TITLE
No connection to instances

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate_mobile#157]
On **Android 7** , it is not possible to connect to instances. After tapping the "Translate" button, I get the message:

> Something went wrong
> 
> Check instance.

Internet connection only via Wi-Fi.

**Comment by ManeraKai** [comment]
Found this: https://flutter-developer.medium.com/flutter-android-7-certificate-verify-failed-with-letsencrypt-ssl-cert-after-sept-30-2021-9cb5f672c090
Working on it.

**Comment by ManeraKai** [comment]
Fixed in https://github.com/ManeraKai/simplytranslate_mobile/commit/ed29db5ed627630599e0c21acd501d8a26f145e0.

Hopefully: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1429740226

**Comment by Valdnet** [comment]
Works correctly 👍.
