### ISSUE TITLE
Version 1.1.0 borks the app language

### ISSUE THREAD

**Issue by shoddysheep** [ManeraKai/simplytranslate_mobile#159]
Hi there.

The latest version from F-droid, v. 1.1.0 from October 3rd automatically sets my app to some Arabic language. I have absolutely no freaking idea what anything says. The language before was English and my phone's app is set to Danish. Rolling back to version 1.0.0 fixes it for the time being.

**Comment by Valdnet** [comment]
I propose to install version 1.1.2.

**Comment by ManeraKai** [comment]
It was fixed here #131.

**Comment by shoddysheep** [comment]
Sorry for the very late reply, and even more sorry for not checking the existing issues before opening a new one. Thank you very much for the response, and thank you for the work on the app. :)
