### ISSUE TITLE
Gray application window

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate_mobile#160]
After starting the application and leaving it for a long time, e.g. after waking up the smartphone, the editing windows for text do not appear in the application (only gray background). It also happens sometimes when choosing a language. In order to restore the correct operation of the application, you must clean the application data.

![obraz](https://user-images.githubusercontent.com/47037905/141687271-fef868e8-f151-42e6-98ab-217e4fb0af2e.png)

App:
Android 10
SimplyTranslate Mobile 1.1.2

**Comment by ManeraKai** [comment]
It happened to me before some days that it won't even start, just a black screen. I'll see about that.

**Comment by ManeraKai** [comment]
can you press the 3-dots though?

**Comment by Valdnet** [comment]
> can you press the 3-dots though?

Yes, I can choose the menu.

**Comment by ManeraKai** [comment]
Wasn't able to reproduce it, I tried to clean up the code to unhide any errors https://github.com/ManeraKai/simplytranslate_mobile/commit/1daa55f1bea5b18f0fa75ef0d7a37375fc1592c0.

**Comment by Valdnet** [comment]
I will test. Maybe there will be some repetition :wink:.

**Comment by Valdnet** [comment]
Steps:
1. Launch the application.
2. Change the language for the source translation text.
3. Put your smartphone to sleep.
4. Wake up the smartphone.

**Comment by Valdnet** [comment]
In the artifact version, I was unable to get an error. I think the problem is only in version 1.1.2.

**Comment by wolftea778** [comment]
I just installed the app and opened it. Thats how it look like:

![Imagepipe_4](https://user-images.githubusercontent.com/96270132/146466009-b979ebc1-d515-4221-acbd-8ddd0ea512cf.jpg)
The settings are working. But if i type on default share language tge screen become grey:

![Imagepipe_5](https://user-images.githubusercontent.com/96270132/146466379-4504c850-c9d1-4cd4-82c9-5ec4277c6da3.jpg)
Info:
Android 8.
App version: 1.1.3

**Comment by Valdnet** [comment]
wolftea778 Clear application memory in settings and restart.

ManeraKai Has to be solved.

**Comment by wolftea778** [comment]
> @wolftea778 Clear application memory in settings and restart.
> 
> @ManeraKai This problem needs to be solved.

I did it. The problem is still there.

**Comment by ManeraKai** [comment]
> ![Imagepipe_5](https://user-images.githubusercontent.com/96270132/146466379-4504c850-c9d1-4cd4-82c9-5ec4277c6da3.jpg) Info: Android 8. App version: 1.1.3

They seem as they're there, but a grey layer is on top.

**Comment by ManeraKai** [comment]
I'll see what can be done.

**Comment by ManeraKai** [comment]
I think it may be a splash screen problem. I've removed the splash screen completely since I don't need it in the first place.
Debug doesn't have splash screen, here a release version.
Compiled unsigned release apk: https://send.turingpoint.de/download/5ccbbf4dd5af669f/#Amuy74leycKD5Jp2JiW1Mg

**Comment by wolftea778** [comment]
> > ![Imagepipe_5](https://user-images.githubusercontent.com/96270132/146466379-4504c850-c9d1-4cd4-82c9-5ec4277c6da3.jpg)
> 
> They seem as they're there, but a grey layer is on top.

Yeah. Thats when i try to change language.

**Comment by wolftea778** [comment]
> I think it may be a splash screen problem. I've removed the splash screen completely since I don't need it in the first place. Debug doesn't have splash screen, here a release version. Compiled unsigned release apk: https://send.turingpoint.de/download/5ccbbf4dd5af669f/#Amuy74leycKD5Jp2JiW1Mg

Maybe to the change language screen problem.
But what about the main?. When i dont see anything when i open the app?.
I download it. It cant be installed on my phone.

**Comment by ManeraKai** [comment]
>  I download it. It cant be installed on my phone.
Because it's unsigned, you should accept some warning messages.

**Comment by ManeraKai** [comment]
> Maybe to the change language screen problem.

I really don't have anything suspicious in the source code that may cause this error. It's really weird.

**Comment by ManeraKai** [comment]
Another inspection and I see a weird widget: 
![image](https://user-images.githubusercontent.com/40805353/146672255-456d19a5-769b-4394-9291-95d8a07ed0ec.png)
`Material` I don't know when I added it.

**Comment by Valdnet** [comment]
> I download it. It cant be installed on my phone.

Please uninstall the previous version of the application first, then install the new one. Remember that you must have an installation from an unknown source selected in the settings.

**Comment by ManeraKai** [comment]
Lastest version: https://send.vis.ee/download/65d07a0e29dfb260/#DEU31QsGTHklWNG6eWD2fg

**Comment by wolftea778** [comment]
> > I download it. It cant be installed on my phone.
> 
> Because it's unsigned, you should accept some warning messages.

Yeah. I got error

**Comment by wolftea778** [comment]
> > I download it. It cant be installed on my phone.
> 
> Please uninstall the previous version of the application first, then install the new one. Remember that you must have an installation from an unknown source selected in the settings.

I did. It just stop in the middle and says: app not installed. 
Thats all hhhhh

**Comment by wolftea778** [comment]
I just now thought on changing the phone from my native language to english. And now its work. The app that i installed from f droid is working.
Sorry for the troubles. Thanks for all your hard work and and quick replays :).
My language is writing from right to left(Hebrew) i dont know if its a problem for all of these types of languages or just for this one. Good luck!

**Comment by ManeraKai** [comment]
So it seems as a system language problem. Hmm...

**Comment by austinhuang0131** [comment]
Having the same issue with system language as Chinese (Simplified) so I don't think it's an RTL problem

**Comment by ManeraKai** [comment]
@austinhuang0131
Have you tried this version?:
https://github.com/ManeraKai/simplytranslate_mobile/issues/160#issuecomment-997433943

**Comment by ManeraKai** [comment]
I think there is an error the is explained well but because it's in release mode it ignores those errors.

**Comment by ManeraKai** [comment]
@elig0n Does it still happen with this version? https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1674916774

**Comment by ManeraKai** [comment]
Does this problem exist in 1.3.0?

**Comment by Valdnet** [comment]
The problem still occurs the first time the application is run.

**Comment by ManeraKai** [comment]
1.4.0? :')

**Comment by Valdnet** [comment]
After upgrading from version 1.3 to version 1.4, they will appear after selecting "Settings" from the menu. In order for the settings to be visible, the application memory must be cleared.

**Comment by ManeraKai** [comment]
Yes bc I removed the camera icon and that made a bug, but is there any other previous reason?

**Comment by Valdnet** [comment]
I'm testing the app :wink:.
