### ISSUE TITLE
[Feature request] Tap to translate

### ISSUE THREAD

**Issue by ygz213** [ManeraKai/simplytranslate_mobile#162]
I think app would be better if it has tap-to-translate-like feature.

**Comment by ManeraKai** [comment]
You mean a share button, or in the text selection tool bar?

**Comment by ygz213** [comment]
I mean a feature that pops a button up when text to translate is copied (Official Google Translate app has this)

**Comment by ManeraKai** [comment]
You can select a text and from the selection toolbar press on the `SimplyTranslate Mobile` button. Not the exact same feature though.

**Comment by ManeraKai** [comment]
@ygz213 Are you there budy?

**Comment by ygz213** [comment]
@ManeraKai sorry for being late, let me close this if you decided not to add.

**Comment by ManeraKai** [comment]
No I'm trying to understand what it's exactly.

**Comment by ygz213** [comment]
I tested now, Google Translate shows a button in the text selection toolbar on newer device, however it pops a button up when text to translate is copied on older device (I opened this issue via older one)

So what I mean is:

> in the text selection tool bar?

**Comment by ygz213** [comment]
I confirmed there it is, but it can be just a window instead of opening app to be more useful like this: 

https://user-images.githubusercontent.com/77006222/148425256-c4aabcd6-05ca-440c-bdce-f018898282c6.mp4

**Comment by ManeraKai** [comment]
I understand. Will try to make it just a minimizable popup.
