### ISSUE TITLE
Release 1.1.4

### ISSUE THREAD

**Issue by ManeraKai** [ManeraKai/simplytranslate_mobile#168]
@Valdnet I think a new version should be released. Will keep working on the requested features though.

**Comment by Valdnet** [comment]
I think a new version can be released 😉. Among other things, new translations and corrections were added.

**Comment by ManeraKai** [comment]
The camera feature was added too.

**Comment by Valdnet** [comment]
Is this feature complete? I haven't tested this feature yet 😁.

**Comment by Valdnet** [comment]
Please add the following strings to your translation:

https://github.com/ManeraKai/simplytranslate_mobile/blob/71be50117a38918f0307f854bf0c64fd8379e1cb/lib/google/widgets/translation_input/widgets/camera.dart#L88
https://github.com/ManeraKai/simplytranslate_mobile/blob/71be50117a38918f0307f854bf0c64fd8379e1cb/lib/google/widgets/translation_input/widgets/camera.dart#L92
https://github.com/ManeraKai/simplytranslate_mobile/blob/71be50117a38918f0307f854bf0c64fd8379e1cb/lib/google/widgets/translation_input/widgets/camera.dart#L101
https://github.com/ManeraKai/simplytranslate_mobile/blob/71be50117a38918f0307f854bf0c64fd8379e1cb/lib/google/widgets/translation_input/widgets/camera.dart#L120

Should be changed:
`aren't -> are not`

**Comment by ManeraKai** [comment]
> Is this feature complete? I haven't tested the camera function yet grin.

Not as mature as GoogleTranslate's one, but it's good for a first release.

**Comment by Valdnet** [comment]
Please also add these text strings for translation:

https://github.com/ManeraKai/simplytranslate_mobile/blob/ba123f448022d6c4176beeb6c491fd088e4350a0/lib/screens/settings/widgets/text_recognition.dart#L22-L23

> Not as mature as GoogleTranslate's one, but it's good for a first release.

I am testing and I am full of admiration 😉.

**Comment by Valdnet** [comment]
When downloading all languages, the languages that have already been downloaded are downloaded again (the download progress wheel informs you about it):

![obraz](https://user-images.githubusercontent.com/47037905/148834863-bda39745-b397-40d5-b127-4cceb91988f6.png)
![obraz](https://user-images.githubusercontent.com/47037905/148835044-18b48af0-5864-48eb-aeac-b03f1ea71027.png)

**Comment by ManeraKai** [comment]
> This variable ${fromSelLangMap[fromLangVal]!} should be simplified for translators. As was done for other text strings.

Simplified it to `Text Recognition - $language`

**Comment by Valdnet** [comment]
> Simplified it to Text Recognition - $language

In the `arb` files, the text string must be changed to the correct one.

https://github.com/ManeraKai/simplytranslate_mobile/blob/8ca24c7b3fd4d31819040bd382ff7237c763f357/lang/main_en.arb#L166

**Comment by ManeraKai** [comment]
Didn't commit it yet.

**Comment by ManeraKai** [comment]
Matured the camera too. Anything else @Valdnet. This release is just for F-Droid users to keep up. I will complete working on the other things.

**Comment by Valdnet** [comment]
Before releasing a new version, remember to merge #167.
And should be improved yet https://github.com/ManeraKai/simplytranslate_mobile/issues/169#issuecomment-1013905080.

**Comment by Aga-C** [comment]
The Translation section on the website should be updated to contain the link to Weblate 🙂

**Comment by Valdnet** [comment]
On the application page, you also need to change the link to Weblate.

**Comment by ManeraKai** [comment]
@Valdnet @Aga-C updated the links in the app and website.

**Comment by Valdnet** [comment]
The application has been successfully tested 👍. You can release a new version 😉.

**Comment by ManeraKai** [comment]
Added the site's translation strings to Weblate too.

**Comment by Aga-C** [comment]
@ManeraKai I've just noticed that some strings I've changed for website and main on Weblate have been reverted to old versions. I've just fixed them again, but why did it happen?

**Comment by ManeraKai** [comment]
Oh, I think because I reseted it. Really sorry for that.

**Comment by Aga-C** [comment]
Ok, no problem. It was easy to revert it 🙂

**Comment by ManeraKai** [comment]
I'll just fix some things in the website and we're ready to go!

**Comment by Valdnet** [comment]
On the website, under "Want to Donate?" you have swapped links or buttons 😉.

**Comment by ManeraKai** [comment]
@Valdnet Fixed them and finished working with the site.

**Comment by ManeraKai** [comment]
Fly my Wind Assassin! 🚀
https://github.com/ManeraKai/simplytranslate_mobile/releases/tag/v1.1.4

**Comment by ManeraKai** [comment]
One last thing if you can add the Camera Text Recognition in Polish in the metadata @Valdnet @Aga-C .

**Comment by ManeraKai** [comment]
Isn't it a little weird that f-droid didn't update the version?

**Comment by Aga-C** [comment]
Maybe you should ask them on their GitLab.
