### ISSUE TITLE
Text Recognition

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate_mobile#169]
Steps:
1. Turn off data transfer.
2. Tap on the camera icon.
3. Select "Install".
4. Go to settings.
5. Select "Text Recognition".

Information about the downloaded language is displayed even though it was not installed:

![obraz](https://user-images.githubusercontent.com/47037905/148837672-3e43a2f4-5a48-41e3-816f-ae02d6125243.png)

**Comment by Valdnet** [comment]
When downloading all languages, the languages that have already been downloaded are downloaded again (the download progress wheel informs you about it):

![obraz](https://user-images.githubusercontent.com/47037905/148834863-bda39745-b397-40d5-b127-4cceb91988f6.png)
![obraz](https://user-images.githubusercontent.com/47037905/148835044-18b48af0-5864-48eb-aeac-b03f1ea71027.png)

**Comment by ManeraKai** [comment]
Should I keep the download all feature. It really is just for someone that wants to play. No one will use it IRL. I'm saying that because the `download all` is a little bit complicated.

**Comment by Valdnet** [comment]
It must be clear to the user what he has downloaded and what else he can download despite whether or not this feature will be used frequently. If we already add such an option, it must work properly 😉.

**Comment by ManeraKai** [comment]
I just meant the download all button.

**Comment by Valdnet** [comment]
> I just meant the Install all button.

OK. The button itself tells the user that it is installing everything.

**Comment by ManeraKai** [comment]
OK, I will fix it.

**Comment by Valdnet** [comment]
> OK, I will fix it.

I don't know if you got me right. The "Install all" problem may stay that way. The user choosing to install everything is aware that he is installing all languages. And whether it re-installs them, or just the ones that are already installed, it doesn't really matter. The user only wastes a little time downloading.

But the problem described in the first post should be corrected.

**Comment by ManeraKai** [comment]
Still maturing it but I think the problem is fixed: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1701929155

**Comment by ManeraKai** [comment]
I may deleted `install all` for now. Don't worry, I will added it

**Comment by ManeraKai** [comment]
Or should I? I'm really not seeing a purpose from it.

**Comment by Valdnet** [comment]
While installing "Text Recognition", I cannot see the download progress bar as it was before:

![obraz](https://user-images.githubusercontent.com/47037905/149668217-5a41f6c1-9ed9-4dff-8367-b13f8f4679e2.png)

**Comment by ManeraKai** [comment]
I think it works in this one: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1704801468

**Comment by Valdnet** [comment]
Steps:

1. Select the camera icon.
2. Select "Install".
3. Select "Cancel".
4. Go to the application settings.
5. Select "Text Recognition".


The download completes even though the installation is canceled.

**Comment by ManeraKai** [comment]
Fixed: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1705212904

**Comment by Valdnet** [comment]
Steps:
1. Select "Settings".
2. Select "Text Recognition".
3. Tap on any language to install.

During the language installation, the button (installation progress) is still active and you can tap continuously, which causes the language installation process to be repeated.

**Comment by ManeraKai** [comment]
Fixed: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1708623672

**Comment by Valdnet** [comment]
Steps:

1. Tap the camera icon.
2. Select "Install".
3. Once installed, go to the "Text Recognition".

The icon for the installed language does not change.

**Comment by ManeraKai** [comment]
Isn't this the same as the first bug?

**Comment by ManeraKai** [comment]
Np: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1709182922

**Comment by Valdnet** [comment]
Can these messages be added to the translation so that they are meaningfully understood by the user?

These are messages from a ready plug-in and download content from Android.

![obraz](https://user-images.githubusercontent.com/47037905/149902220-3ab0717f-0cf4-49f1-8220-ece3c8e13314.png)
![obraz](https://user-images.githubusercontent.com/47037905/149902331-8b75ad97-af6f-4a4a-952a-94c8845e28b4.png)

**Comment by ManeraKai** [comment]
The second one should is too technical I think. The first one I'll search for it.

**Comment by Valdnet** [comment]
> Here are they. Apparently they're untranslatable, but I can add something like if (camera.isGranted())

Good idea 👍. This will resolve unreadable error messages 😉.

**Comment by ManeraKai** [comment]
Did that: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1715274831

**Comment by Valdnet** [comment]
Successful tests 👍. I am closing the issue.

**Comment by Valdnet** [comment]
Steps:
1. Run "Text Recognition".
2. Turn the smartphone over to a horizontal position.
3. Take a picture of the text.
4. Place the smartphone vertically.
5. 
Sometimes the application window does not return to a vertical position. The application stops after a long time.

![obraz](https://user-images.githubusercontent.com/47037905/150085724-a6d3ee24-ca02-4881-8f67-9cbf84a5c626.png)

**Comment by Aga-C** [comment]
Translations are blocked on Weblate ("main" component).

**Comment by ManeraKai** [comment]
@Aga-C it got some conflicts because I added a new string. Will fix it.

**Comment by ManeraKai** [comment]
> Translation is blocked on Weblate ("main" component).

Fixed it... Hopefully.

**Comment by ManeraKai** [comment]
@Valdnet Fixed it too: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1718532979

**Comment by Valdnet** [comment]
Steps:

1. Run "Text Recognition".
2. Turn the smartphone over to a horizontal position.
3. Take a picture of the text.
4. Place the smartphone vertically.
5. Turn the smartphone over horizontally again.

The camera image does not extend to the entire screen:

![obraz](https://user-images.githubusercontent.com/47037905/150337521-22d72a1b-fe71-465b-a141-25758adc817c.png)

**Comment by ManeraKai** [comment]
I think this has something to do with skipping frames due to overload on the main thread. I will begin optimizing the `tesseract_ocr` in the next release. What do you think @Valdnet?

**Comment by Valdnet** [comment]
It also seems to me that this is a performance issue (it could be due to the development version). So the tests are complete. A new version can be released 😉.

Issue to close?

**Comment by ManeraKai** [comment]
No, keep it open as we'll complete improving it unless you want to open a dedicated issue for performance thingies.

**Comment by Valdnet** [comment]
We will leave him open to possible issues 😉.

**Comment by tswistak** [comment]
Unfortunately, for me, it doesn't work. When I take a photo loader appears and then apps hangs (there is this Android window that app is not responding). Even if I click "Wait", app crashes after a while.

**Comment by Aga-C** [comment]
The text recognition usually works very slow and can hang a bit. After recognition, it sometimes selects some noise what causes displaying strange characters during translation - it seems that it depends on the sharpness of the text and surface.

**Comment by Valdnet** [comment]
> When I take a photo, loader appears and then apps hangs (there is this Android window that app is not responding).

I had such frequent crashes on the debug version.

**Comment by ManeraKai** [comment]
This needs optimization and some improvements on text recognition.
