### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [ManeraKai/simplytranslate_mobile#170]
https://hosted.weblate.org/projects/hglauncher/#information says GPLv3-only,
whereas https://manerakai.github.io/simplytranslate_mobile/
and
https://github.com/ManeraKai/simplytranslate_mobile/search?q=or+later
says GPLv3-or-later

it can be changed (to GPLv3+) in
https://hosted.weblate.org/settings/simplytranslate-mobile/main/
https://hosted.weblate.org/settings/simplytranslate-mobile/glossary/
by @ManeraKai

**Comment by ManeraKai** [comment]
Changed them.
