### ISSUE TITLE
Import translations of language names from Weblate

### ISSUE THREAD

**Issue by comradekingu** [ManeraKai/simplytranslate_mobile#171]
https://hosted.weblate.org/projects/weblate/languages/#translations has all the language names, most of which are duplicated in https://hosted.weblate.org/projects/simplytranslate-mobile/main/
(actually over 70% of those strings)
If not, it should use or ask to change the Weblate variants.

I can help set up the plugin if you add "kingu" in https://hosted.weblate.org/access/simplytranslate-mobile/ :)

The issue is that when not translating all the names, new strings are missed, and end up at the bottom.
Setting string-priority would help with the sorting, but still.

**Comment by ManeraKai** [comment]
I really didn't understand

**Comment by comradekingu** [comment]
I am saying in https://hosted.weblate.org/projects/simplytranslate-mobile/main/ language names (Portuguese, German, Italian, and so on) are already translated.
These names can be imported into https://hosted.weblate.org/project/simplytranslate-mobile/ so that translator don't have to do the work twice.
I offered to do so, but you can also configure the plugin, since you are a Weblate admin for the project.

**Comment by ManeraKai** [comment]
This is my first time being an admin on weblate. It will be really nice if you can help!

**Comment by comradekingu** [comment]
I turned on shared translation memory and imported the nb_NO strings manually.
[The plugin](https://hosted.weblate.org/addons/simplytranslate-mobile/main/) isn't needed and I couldn't select just one component to import from anyway.

**Comment by comradekingu** [comment]
I think maybe splitting all the languages out to a separate component and then import into that would do.

**Comment by ManeraKai** [comment]
hmm...

**Comment by Valdnet** [comment]
@ManeraKai Thank you for the new permissions on Weblate 😉.

**Comment by ManeraKai** [comment]
@comradekingu You mean like this? 
![image](https://user-images.githubusercontent.com/40805353/149824222-cc101698-62f2-42da-9064-0675ab0b9742.png)

**Comment by comradekingu** [comment]
@ManeraKai Yes. If you add that in addition to the current component first, I can try to auto-import to it. :)

**Comment by ManeraKai** [comment]
>  in addition to the current component first

?

**Comment by comradekingu** [comment]
@ManeraKai Right now all the languages are in https://hosted.weblate.org/projects/simplytranslate-mobile/main/
If there was also a /simplytranslate-mobile/languages/ then we could to set that up to import new languages automatically. Then if that works, the languages can be removed from the "simplytranslate/main" component :)

**Comment by ManeraKai** [comment]
Didn't find a way to split arb files neither in weblate nor in Flutter. So wrote a small python script to merge them.
![image](https://user-images.githubusercontent.com/40805353/149943954-4acc0261-5584-4239-832d-2b6c0253343a.png)
@comradekingu 👍

**Comment by comradekingu** [comment]
Translations for empty fields are "OrderedDict()" https://hosted.weblate.org/zen/simplytranslate-mobile/langs/nb_NO/?offset=1&q=state%3Aempty

**Comment by ManeraKai** [comment]
Weird: That word isn't from the `.arb` files: https://github.com/ManeraKai/simplytranslate_mobile/blob/main/lib/l10n/intl_nb_NO.arb

**Comment by ManeraKai** [comment]
Seems just in your language: 
![image](https://user-images.githubusercontent.com/40805353/149972969-470187d9-811c-4cec-a133-c02383db36c1.png)

**Comment by ManeraKai** [comment]
Removed them.

**Comment by ManeraKai** [comment]
Does anyone have an idea of why Weblate isn't able to push to the repo? It was fine yesterday @Valdnet @Aga-C @comradekingu

**Comment by Valdnet** [comment]
For me, Weblate is incomprehensible. Generally, I don't like translating and operating in it. The design itself would not pass my tests 😁.

**Comment by ManeraKai** [comment]
I'm struggling too, I really don't know what to do now with this problem.

**Comment by Valdnet** [comment]
Maybe @comradekingu will help you 😉.

**Comment by Aga-C** [comment]
@ManeraKai Maybe ask here: https://github.com/WeblateOrg/weblate/issues/new/choose.

**Comment by ManeraKai** [comment]
@Aga-C @Valdnet  Asked and was able to fix it: https://github.com/WeblateOrg/weblate/issues/7129

**Comment by ManeraKai** [comment]
@comradekingu Is there anyway of listing out contributors like in POEditor?

**Comment by comradekingu** [comment]
@ManeraKai https://docs.weblate.org/en/latest/devel/reporting.html#translator-credits
It is also possible to have a translator-credit string in the About section so translators can add themselves if they want.
