### ISSUE TITLE
Quick translation

### ISSUE THREAD

**Issue by Barmarel** [ManeraKai/simplytranslate_mobile#187]
Please add the ability to quickly translate copied text, like it is implemented in the official Google Translate app.

**Comment by Aga-C** [comment]
Isn't it the same as #162?

**Comment by ManeraKai** [comment]
It's there, when the textselection toolbar pops up, you will have an option called `SimplyTranslate Mobile` press and it will open the app with the copied text.

> Isn't it the same as #162?

The difference with that issue is that he wants it to be a window popup rather than opening the whole app.

**Comment by Barmarel** [comment]
> you will have an option called `SimplyTranslate Mobile`
Unfortunately, this feature does not appear everywhere in the panel. Especially often it is missing when text is copied in applications other than the browser.

> a window popup rather than opening the whole app.
Or better yet, a pop-up button that will bring up a pop-up dialog box with a translation. As it is done in the original Google app.
I agree that it will be copying the function, but it is the most convenient solution.

**Comment by ManeraKai** [comment]
@Aga-C [he said](https://github.com/ManeraKai/simplytranslate_mobile/issues/162#issuecomment-1006774665) that it can be a window popup so as you've said, same feature. Will close this and complete the work on #162
