### ISSUE TITLE
Moving SimplyTranslate-Mobile under the Simple-Web foundation

### ISSUE THREAD

**Issue by ManeraKai** [ManeraKai/simplytranslate_mobile#188]
I want to discuss that with you guys and ladies I should say? @Valdnet @Aga-C

There will be some talking the group [#simple-web:libera.chat](https://matrix.to/#/#simple-web:libera.chat), btw you can Element (matrix client) to access IRC.

**Comment by Aga-C** [comment]
Do what's the best for you and the app 👍

**Comment by Valdnet** [comment]
I'm for it 👍.

**Comment by ManeraKai** [comment]
I was concerned that this may affect our decision making inside the project. I asked him about it and he that this won't happen.

He also suggested that the repo may be moved to [github.com/Simple-Web-Project/SimplyTranslate-Mobile](http://github.com/Simple-Web-Project/SimplyTranslate-Mobile), personally I'm against this. I'm a little bit afraid of that and I like to own the repo under my account name. I suggested mirroring it instead.

I'm now thinking of just linking it like I have LibRedirect in my account's repo pins although I don't own it but part of the organization.

What do you think @Aga-C @Valdnet?

**Comment by Valdnet** [comment]
> He also suggested that the repo may be moved to github.com/Simple-Web-Project/SimplyTranslate-Mobile, personally I'm against this. I'm a little bit afraid of that and I like to own the repo under my account name. I suggested mirroring it instead.

If you want to stay in your repository, it is imperative not to change it.

**Comment by metalune1** [comment]
I'm not familiar with how linking in github works, if that also mirrors Issues, I don't see that big of a problem with you staying here on this repository I guess :)

**Comment by Aga-C** [comment]
@Valdnet I just got a notification, that you've mentioned me on the new repository, but I don't have an access there...

**Comment by ManeraKai** [comment]
Was it something like this @Aga-C? https://github.com/Simple-Web-Project/SimplyTranslate-Mobile

**Comment by Aga-C** [comment]
@ManeraKai Yes, and I get 404 on that.

**Comment by ManeraKai** [comment]
@metalune1 was trying to pin my Repo to his [organization](https://github.com/Simple-Web-Project) as we're transitioning to it today. He accidentally cloned the Repo instead of just pinning it.

**Comment by Aga-C** [comment]
@ManeraKai Maybe you need to transfer repository to the organization?

**Comment by ManeraKai** [comment]
I know but ...
![image](https://user-images.githubusercontent.com/40805353/154854054-d28bd8a2-1096-48d1-a74f-260de4e30ff4.png)
This is another approach

**Comment by ManeraKai** [comment]
SimplyTranslateMobile has been moved to the [Simple Web Foundation](https://simple-web.org/) but the Repo will stay here.
It's been linked under the [SimplyTranslate](https://simple-web.org/projects/simplytranslate.html) page as `SimplyTranslate Android App`.

Thank you guys!
