### ISSUE TITLE
App doesn't run after latest update

### ISSUE THREAD

**Issue by tswistak** [ManeraKai/simplytranslate_mobile#189]
Hi,

I've just updated the app via F-Droid to the latest version, and it can't run. I just get a black screen and nothing shows. 

Tried to clear app's memory etc. and it doesn't help. My phone is OnePlus 8 Pro, with Android 11 (not rooted).

**Comment by Aga-C** [comment]
@ManeraKai Maybe it was some sign that F-Droid couldn't read that there is a new release 🙂

BTW. I have this issue too.

**Comment by Seferi** [comment]
Same here... Updated and getting a black screen upon launch..

**Comment by ManeraKai** [comment]
I think it's just a version problem. I was using version `2.8.12` when it's in fdroid's build metadata `2.10.0`. Will fix that.

**Comment by Seferi** [comment]
Latest version on f-droid is 1.1.4 which I updated to...

**Comment by ManeraKai** [comment]
Updated it in this commit: https://github.com/ManeraKai/simplytranslate_mobile/commit/dcab87019e7c844a538bfb3a29c08c65c1be607e

**Comment by maemunman** [comment]
I apologize for bearing bad news, but 1.2.0 also does not work.  Same blank screen when you open the app as 1.1.4

**Comment by tswistak** [comment]
I don't have blank screen anymore in 1.2.0, but the app hangs and then crashes while trying to recognize text from the photo.

**Comment by Aga-C** [comment]
In my case, at the first launch I have a blank screen, but after reopening the app again it works without any problems.

**Comment by Valdnet** [comment]
> In my case, at the first launch I have a blank screen, but after reopening the app again it works without any problems.

The same problem repeats for me as well.

Apps:
Android 10
SimplyTrtanslate Mobile 1.2.0

**Comment by maemunman** [comment]
@tswistak I tried that and it worked.  I had to kill the app, without clearing cache or data.  The app works now.

**Comment by ManeraKai** [comment]
Any further discussion about the blank screen will be completed in the original issue: #160. I'll close the issue as it's running right now.
