### ISSUE TITLE
Add hints for text recognition

### ISSUE THREAD

**Issue by Aga-C** [ManeraKai/simplytranslate_mobile#190]
I think it would be very useful to add 2 hints related to this function:
- a tooltip for the inactive camera icon on the main screen - to tell the user that he should change the source language from "Autodetect" to another to be able to use this function
![image](https://user-images.githubusercontent.com/85929121/154473285-13f2dcf9-0190-4db2-874f-71b0ca9264f5.png)
- a help icon at the top of the text recognition screen - after tapping it, the popup opens with the information how to use the tool
![image](https://user-images.githubusercontent.com/85929121/154473583-68d41412-d778-4780-b27f-c434d1ca2a0b.png)

**Comment by ManeraKai** [comment]
The second picture has a bug that I saw too.

**Comment by ManeraKai** [comment]
I've fixed that weird bug.
> a help icon at the top of the text recognition screen - after tapping it, the popup opens with the information how to use the tool

It's just drawing. Was it weird for you at the beginning @Aga-C?

**Comment by ManeraKai** [comment]
Added a hint for the camera: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2047328527

btw I really like the `AlertDialog` more than the little notification at the bottom that is called `SnackBar`. I may change everything like that so the user won't unnotice it unintentionally.

**Comment by Aga-C** [comment]
> It's just drawing. Was it weird for you at the beginning @Aga-C?

Nothing says so, it's not intuitive. At first, I thought that it's clicking to select. There should be any hint saying that it's drawing.

> Added a hint for the camera

I'd change the text a bit. `Please select another language` implies that autodetect is a language. Also, the dot is missing at the end. Maybe `Please select a specific language.`?

**Comment by ManeraKai** [comment]
What should be the text for informing the user about how to draw?

**Comment by ManeraKai** [comment]
This is my text:
`Paint the green boxes with your finger. The parts where the paint touch are registered`

**Comment by Aga-C** [comment]
`Select text to translate by drawing on the screen.`

**Comment by ManeraKai** [comment]
Alright: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2047639814

**Comment by Aga-C** [comment]
Looks ok 👍 BTW. Why there is no OK button on the dialog?

**Comment by ManeraKai** [comment]
oh forgot that. Will added it

**Comment by ManeraKai** [comment]
![image](https://user-images.githubusercontent.com/40805353/160280807-2dd93952-8d05-406d-a0ee-826d5507d0cf.png)
