### ISSUE TITLE
Texts after certain characters are not translated

### ISSUE THREAD

**Issue by cc713** [ManeraKai/simplytranslate_mobile#192]
AFAIK texts after `&` and `#` are not translated, while the web version works fine. Maybe some other characters also have this issue.

**Comment by ManeraKai** [comment]
Escaping problem I think

**Comment by Valdnet** [comment]
I confirm the problem in version 1.2.0.

**Comment by Valdnet** [comment]
When translating `#` and `&` the translation is incomplete. It ends before these signs:

![obraz](https://user-images.githubusercontent.com/47037905/156743415-9d94fa70-0efb-4f2c-9683-890d61c6bdab.png)
![obraz](https://user-images.githubusercontent.com/47037905/156743353-d1173f1d-afa4-4a33-8ee0-a30a5933a416.png)

Apps:
Android 10
SimplyTranslate Android 1.2.0

**Comment by ManeraKai** [comment]
I tested it and it's fixed now: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1939323142

**Comment by Valdnet** [comment]
Works properly 👍.
