### ISSUE TITLE
GUI too large.

### ISSUE THREAD

**Issue by Git-Forked** [ManeraKai/simplytranslate_mobile#193]
## Problem:
The graphical interface is too large.
This is annoying and reduces efficiency when using the app.

## Possible Solution(s): 
- Reduce the size of the input text boxes.
- Move icons to a row, instead of in a column.
- Move Translate button to the top. (or don't even show it at all, and have it only appear above the keyboard)

**Comment by ManeraKai** [comment]
When you're typing the keyboard is opened, the translate button goes up to the top part of the keyboard

**Comment by Git-Forked** [comment]
That's true, but it would be more convenient and look nicer to have all of the GUI fit inside the screen without having to scroll. 
It's only slightly too big, so why not resize it to actually fit properly?

**Comment by ManeraKai** [comment]
How much is your Font Size in the accessibility options in your android? This setting resizes everything for all apps.

**Comment by Git-Forked** [comment]
My font is default size, but even on the smallest size, the GUI is too large for the screen.

**Comment by ManeraKai** [comment]
I see, I'll see what I can do.

**Comment by Git-Forked** [comment]
I'm going to send you some pictures, so you can see what I am seeing.

**Comment by Git-Forked** [comment]
mtp:/Galaxy A01/Phone/DCIM/Screenshots/Screenshot_20220311-132837.jpg
mtp:/Galaxy A01/Phone/DCIM/Screenshots/Screenshot_20220311-132845.jpg

**Comment by Git-Forked** [comment]
Scrolled to the top: 
![Screenshot_20220311-132837](https://user-images.githubusercontent.com/66106762/157931560-30d1272f-e507-4d6d-a99b-0e8bc757c014.jpg)
Scrolled to the bottom: 
![Screenshot_20220311-132845](https://user-images.githubusercontent.com/66106762/157931583-f0641bb5-08d6-4502-8902-3a51deb3d8f1.jpg)

**Comment by Git-Forked** [comment]
> I see, I'll see what I can do.

Thank you, and I appreciate the work you have put into this app, as well as your kindness in considering my suggestion to make the app look better and fit the screen.

**Comment by Git-Forked** [comment]
If you package a version that fixes the issue, I will be glad to test it out for you on my device.

**Comment by ManeraKai** [comment]
I'm now trying to put the icons as a row as you said. But it's not working well design wise:
<img width=400 src="https://user-images.githubusercontent.com/40805353/158564083-98fd446a-f93f-4b6f-9986-b0fb854e5b8d.png">

Everything is cramped now and it looks awful. I have an idea though.

@Valdnet I'll add a setting that is: `Enable Advanced Tools`. This will enable the `paste`, `maximize`, `minimize` icons. Those were you're request and not every user uses them. They still can be enabled though.
How it may look:
<img width=400 src="https://user-images.githubusercontent.com/40805353/158565571-25876d23-bf5d-4aee-bc3a-0c78f57f38aa.png">

What do you think @Valdnet @Git-Forked?

**Comment by Valdnet** [comment]
I propose to hide the character counter and add an option in the settings where the user can enable the visibility of the character counter. I think that the character counter is less needed and the user will get information about exceeding the limit anyway.

Your idea is also good, but there is a lot of unused space in the window with the translated text and the "Paste" icon is used quite often.

**Comment by ManeraKai** [comment]
> I propose to hide the character counter and add an option in the settings where the user can enable the visibility of the character counter. I think that the character counter is less needed and the user will get information about exceeding the limit anyway.

I see.

> Your idea is also good, but there is a lot of unused space in the window with the translated text and the "Paste" icon is used quite often.

How about removing the `maximize`, `minimize` buttons and keeping more tools in the input?

**Comment by Valdnet** [comment]
> How about removing the maximize, minimize buttons and keeping more tools in the input?

I think you can opt out of these buttons. And so these buttons are in the magnified view window.

**Comment by ManeraKai** [comment]
I agree too.

**Comment by ManeraKai** [comment]
<img width=400 src="https://user-images.githubusercontent.com/40805353/158575124-6c928a01-9ce5-42ef-afbf-6e7f81cc63a7.png">

**Comment by Valdnet** [comment]
It looks very good in my opinion 👍.

**Comment by ManeraKai** [comment]
Added it, here it is: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1992538440

**Comment by Git-Forked** [comment]
Why do we need a copy button in the input box?  Wouldn't we only need paste?  Anyways both are available natively on mobile with a long press, but having the paste button seems quicker, so I don't mind that button, but copy button seems like it could be hidden most the time, and enabled with advanced options.  Copy button on the result is fine though, and useful. 

I'm going to install your release and check it out.  Thank you.

**Comment by Git-Forked** [comment]
Any reason why the file is so big now?  Seems it keeps growing. Moving buttons should haven't increased the size.
v1.1.3 was 19.5 MiB
v1.2.0 umped to 79.9 MiB
And this new release you posted above is 135 MB.

**Comment by Valdnet** [comment]
> Why do we need a copy button in the input box? Wouldn't we only need paste?

The copy button is intentionally placed for the window with the text to be translated. It improves the copying of the inverted translation, which consists in the fact that the translated text re-translated into the native language allows you to check the correct translation, which can be immediately copied via the "Copy" button to the phone's memory.

> I'm unable to install this version. I downloaded compiled-flutter-code.zip and extracted from inside it an app-development-debug.apk, but my phone refuses to install it with message: "App not installed"
 (And I do have "Install Unknown Apps" option enabled)

The downloadable application is in a debug version and is not signed. To install this version you must first uninstall the F-Droid version (but you've already dealt with that).

> Any reason why the file is so big now? Seems it keeps growing. Moving buttons shouldn't have increased the size.
> v1.1.3 was 19.5 MiB
> v1.2.0 jumped to 79.9 MiB

v1.1.3 was 19.5 MiB - Version without "Camera Text Recognition"
1.2.0 jumped to 79.9 MiB - Version with "Camera Text Recognition"

> And this new release you posted above is 135 MB.

It is a debug version, so it is much larger.

**Comment by Git-Forked** [comment]
Alright, thank you for answering that.   Also I edited my above post to add the following: 

The space above and below the language selection is more pixels than between text boxes, perhaps the margin space can be made consistent to the smaller size.

**Comment by ManeraKai** [comment]
We didn't add the `advanced options` as we settled on removing buttons from the result output. Seems we're not that settled xD and so I think I should add them as a checklist of which buttons to enable and disable. Seems every person uses translation very very differently.

**Comment by Git-Forked** [comment]
> We didn't add the `advanced options` as we settled on removing buttons from the result output. Seems we're not that settled xD and so I think I should add them as a checklist of which buttons to enable and disable. Seems every person uses translation very very differently.

Yes, I think making it customizable for each person is a good idea. 
Thank you for considering that.

**Comment by ManeraKai** [comment]
This is how it looks: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2044105216

**Comment by Git-Forked** [comment]
That looks really good now and it fits my screen. :D 
The customizable buttons are a great addition.
Excellent work.

**Comment by ManeraKai** [comment]
Nice to hear that! I'll improve on it as it breaks some other things related to the inputs, then will release it. Hopefully soon.

**Comment by Valdnet** [comment]
White icon for camera button in light theme. Tested on: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2047328527.

![obraz](https://user-images.githubusercontent.com/47037905/160353421-820567c7-1ed8-415d-bb3f-25ff403dd8c5.png)

**Comment by ManeraKai** [comment]
> 1. White icon for camera button in light theme:

Fixed before. I think because of the version you tested as you mentioned.

> 2. No icon for counter settings:

I really don't know what to add as an icon: https://fonts.google.com/icons?selected=Material+Icons

**Comment by ManeraKai** [comment]
tbh I may just make a little photo or widget containing that. All the icons are just unrepeatable. As you said it should be the app's counter icon.

**Comment by OkyDooky** [comment]
One option to save space is to have the "Copy" icon/button turn into the "Paste" icon/button when there is no text in the top text-box, then turn back into "Copy" when text is present. We already have the X to quickly cleae text, so that should save the step of having to "Select All" -> "Delete" any existing text.

**Comment by ManeraKai** [comment]
@OkyDooky That would be somewhat complex for the user. Changing buttons order will be confusing imo. What do you think @Valdnet?

**Comment by Valdnet** [comment]
This is some solution, but it is not best for the user. Sometimes the user needs to paste the text many times in different places, e.g. Name or the same words. Such a function with changing the button prevents this and may be a bit unintuitive and confusing for the user. I am for leaving it as it is. The ability to set buttons in the application settings is already a sufficient solution.

**Comment by ManeraKai** [comment]
I agree too.

**Comment by Valdnet** [comment]
@ManeraKai After installing the application from [artifact](https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2189896605), I noticed that the application does not remember the button display settings. After restarting the application, the new settings are ignored.

**Comment by ManeraKai** [comment]
committed here: https://github.com/ManeraKai/simplytranslate_mobile/commit/1f608a7960dcc69e2d13aaf48752b8ece927a13b

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2194473452

**Comment by Valdnet** [comment]
Is this normal in the debug version?

![obraz](https://user-images.githubusercontent.com/47037905/164262485-e0347e55-6139-4789-9f92-ec46f35df075.png)

**Comment by ManeraKai** [comment]
Uninstall it completely with deleting the cache and try again. This is weird.

**Comment by Valdnet** [comment]
The application was previously uninstalled.

**Comment by Valdnet** [comment]
This issue persists in the latest [debug version](https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2229095138).
