### ISSUE TITLE
Instances

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate_mobile#196]
When selecting some instances, e.g.: st.manerakai, st.alefvanoon, translate.namazso e.t.c. translations are not performed - no error information. The error message appears only when the `<->` button is tapped.

This only happens with the app [SimpleTranslate ](https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2192267869) after adding the function from #154.

**Comment by ManeraKai** [comment]
My instance isn't updated as for compatibility. I'll update mine to the new API once I release a new version and will talk to the instances owners to update their instances.

**Comment by Valdnet** [comment]
For instances that are not supported with the new version, the standard message should appear: Something went wrong. Check your instance!

**Comment by ManeraKai** [comment]
We have a finite number of instances and we can manage to let them update. I don't want to be stuck in a version problem. The new API is much more flexible for new features for any engine: https://simplytranslate.org/api/translate/?engine=google&from=en&to=pl&text=House

btw SimpleWeb has  moved to Codeberg: https://codeberg.org/SimpleWeb/SimplyTranslate-Web

**Comment by ManeraKai** [comment]
Seems it was a bug that they weren't showing xD. Anyway I've fixed it.
