### ISSUE TITLE
"Copy" button

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate_mobile#197]
The "Copy" button for the window with the translated text does not work. Application from the [artifact](https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2192267869).

![obraz](https://user-images.githubusercontent.com/47037905/164180915-8df5f0db-e12e-419c-80b0-68e760af0cd9.png)

**Comment by Valdnet** [comment]
Does the latest version of the artifact contain the fix? Currently, the "Copy" button still does not work.

**Comment by ManeraKai** [comment]
No I don't think that I compiled for it.
