### ISSUE TITLE
Results sometimes in json(?) 

### ISSUE THREAD

**Issue by neekless** [ManeraKai/simplytranslate_mobile#198]
Why the results sometimes show as json(I think?)
Sometimes it's normal sometimes it's like this
![Screenshot_20220426-164809](https://user-images.githubusercontent.com/22426822/165261535-3c9e2f6a-bd54-4baa-aa18-a969f3095a82.png)

**Comment by neekless** [comment]
Seems to be instance-dependant. Certain instances produce this result 100% of the time while other instances display properly 100% of the time. But they display properly on the web version.

**Comment by ManeraKai** [comment]
This is because there's a new API for SimplyTranslate. The app does support the new API but I didn't release a new version yet. choose https://st.manerakai.com that is my own instance and it will work fine. I didn't update it for that propose.

**Comment by neekless** [comment]
Oh I see thanks for the response!

**Comment by ManeraKai** [comment]
Version 1.3.0 has been released. I'll talk to the server maintainers to upgrade their instances.
