### ISSUE TITLE
Can't add custom instances

### ISSUE THREAD

**Issue by nuckle** [ManeraKai/simplytranslate_mobile#204]
Version: 1.3.0 (from F-Droid).
Can't add any custom instance.

Example:
![pic-1](https://user-images.githubusercontent.com/37220313/171883332-0dc65a90-5ef9-41ee-9ce0-bb506dfa3515.png)
The instance itself is working
![pic-2](https://user-images.githubusercontent.com/37220313/171883670-1f17cab9-36c4-4842-81a0-7c22d3ff1126.png)

**Comment by ManeraKai** [comment]
Fixed it, just forgot to support the new API: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2435733661

**Comment by ManeraKai** [comment]
Sorry the previous apk failed to build, this will work: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2437857953
