### ISSUE TITLE
New website design

### ISSUE THREAD

**Issue by ManeraKai** [ManeraKai/simplytranslate_mobile#205]
![SimplyTranslate Mobile 2022-06-06](https://user-images.githubusercontent.com/40805353/172215188-b730addb-912f-43db-8bdd-a0da89539b58.png)
![SimplyTranslate Mobile 2022-06-06](https://user-images.githubusercontent.com/40805353/172215258-f50c3a84-1fc1-476a-a7a4-86cfae569aab.png)
![SimplyTranslate Mobile 2022-06-06](https://user-images.githubusercontent.com/40805353/172215340-011d4974-dd5d-441e-be02-7886d01f3421.png)

**Comment by Valdnet** [comment]
Very nice website. Good job 👍.

**Comment by ManeraKai** [comment]
You can see it @Valdnet. I'll fix the translation problem and then close this issue.
