### ISSUE TITLE
No translation at all when clicking the button

### ISSUE THREAD

**Issue by geyr** [ManeraKai/simplytranslate_mobile#209]
SimplyTranslate on Android vers. 9, EMUI OS vers. 9.1.0;
if a text given to the upper frame (German) and then hitting the 'Translate-' ("Übersetze") button, in the 2nd frame (should be translated to Ukrainian) some code appears, but no translation. 
If I use/do the same procedure in the webinterface/browser-window, the translation is done.. . ! ?? 
Only a problem within my cellphone?
Greets, geyr
![Screenshot_20220615_183752_com simplytranslate_mobile](https://user-images.githubusercontent.com/67758188/173885450-9f0c1008-da7d-43bc-a630-0c76e11fcf88.jpg)
#

**Comment by ManeraKai** [comment]
which version are your running?

**Comment by geyr** [comment]
1.2.0

**Comment by ManeraKai** [comment]
Upgrade to 1.3.0 and the issue will be solved 👍️, it's an API incompatibility.

**Comment by geyr** [comment]
Thanks ManeraKai, that's working!
👌
