### ISSUE TITLE
Doesn't launch on latest GrapheneOS

### ISSUE THREAD

**Issue by blogdemoi** [ManeraKai/simplytranslate_mobile#211]
Hi,

I just installed successfully it on my Pixel 4a with GrapheneOS, however, on launching it, it doesn't launch and GrapheneOS asks me to wait or kill the app.

Thank you for any suggestions.

**Comment by ManeraKai** [comment]
which version are you running?

**Comment by ManeraKai** [comment]
Try to clear it's cache.

**Comment by blogdemoi** [comment]
Thank you. It didn't work either, anyway the cache for this app was empty. I installed previous versions but it didn't work. Maybe it is related to GrapheneOS, so I asked on their forum.

**Comment by blogdemoi** [comment]
Solved. What I did is to install first version 1.2.0 (it didn't launch then) then update to 1.3.0 and it successfully launched.
