### ISSUE TITLE
can't add custom instance

### ISSUE THREAD

**Issue by schklom** [ManeraKai/simplytranslate_mobile#213]
I have no idea why i can't manage to add my instance.

There is no information with `logcat`.
The box where I input the URL becomes red and doesn't go away when I click `check`.

The webpage is accessible without problem.

What can I do to make it work?

**Comment by ManeraKai** [comment]
you should put `https://example.com`

**Comment by schklom** [comment]
I did, the address looks like `https://abc.def.org:12345`.
Is there an issue concerning non-standard ports?

I can log the request hitting the reverse-proxy if it helps identifying the issue.

**Comment by ManeraKai** [comment]
one second, there was a similar issue like this #204. Which version are you running?

**Comment by schklom** [comment]
Website -> I build the Docker image yesterday
Your app -> 1.3.0

**Comment by ManeraKai** [comment]
I tried running it as a compiled apk and it worked fine, maybe try it too: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2647767465

**Comment by schklom** [comment]
Thanks :D

To anyone who doesn't have access to the apk (because GitHub deletes artifacts after some time, e.g. the one from last month is not available anymore), you can:
1. fork the repository
2. run the GitHub Action `Flutter build apk`
3. download the artifact
