### ISSUE TITLE
Multiple instances always produce errors

### ISSUE THREAD

**Issue by Ao1Pointblank** [ManeraKai/simplytranslate_mobile#217]
I went through the list 1 at a time, and attempted to translate a simple phrase multiple times to make sure the broken ones are actually borked. 

st.tokhmi.xyz - check instance error
translate.namazso.eu - VERY slow (takes about 40 seconds to translate anything, and then gives error!)
simplytranslate.pussthecat.org - check instance error
translate.northboot.xyz- check instance error
translate.tiekoetter.com- check instance error
translate.beparanoid.de- check instance error

for the ones that give the "check instance error", i visited the website and can confirm that the web frontend of these instances still do work. 

if these can't be fixed, and other users can replicate the same results as me, i'd like to suggest removing them from the list so users can still use the Randomize option.

**Comment by ManeraKai** [comment]
@metalune1
