### ISSUE TITLE
Camera 😔

### ISSUE THREAD

**Issue by Wjxfi** [ManeraKai/simplytranslate_mobile#222]
```Before that I tried to translate with the camera```

after exiting the application, the camera is on. It should have turned off automatically after exiting the application and after completing the translation.

**Comment by Growebis** [comment]
This also happens to me sometimes now that im realizing it, because sometimes when i exit the app the flash is still on which makes me realize that the camera is still on, im not sure what causes the bug to happen, maybe the developer forgot to add a line of code to disable the camera at exit?

**Comment by ManeraKai** [comment]
Removed Text Recognition completely: https://github.com/ManeraKai/simplytranslate_mobile/commit/b46d0eed24121c929746ddb3e51b22c62056315a
