### ISSUE TITLE
Pressing the "update list" button causes an error

### ISSUE THREAD

**Issue by Wjxfi** [ManeraKai/simplytranslate_mobile#223]

**Comment by Growebis** [comment]
This is also happening to me. Just adding my two cents so that the developer can notice

**Comment by Ftonans** [comment]
That's probably because https://simple-web.org/instances/simplytranslate is not available as for now; app tries to fetch info from there, so the error appears

**Comment by fohfuu** [comment]
Both the default instances in the app are no longer functional. These should be replaced or removed so that this does not become a security hazard if one of the domains is bought up by bad actors.

**Comment by ManeraKai** [comment]
I just need to convert this file from python to dart: https://codeberg.org/SimpleWeb/SimplyTranslate-Engines/src/branch/master/simplytranslate_engines/googletranslate.py
