### ISSUE TITLE
Text translation

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate_mobile#227]
In version 1.4 the application does not always translate text.

This may be due to the lack of connection to the instance.
In the current version, I noticed that the option to set instances has been removed from the application.

**Comment by ManeraKai** [comment]
It now connects to google translate directly.

**Comment by Aga-C** [comment]
@ManeraKai Maybe you should use https://github.com/thedaviddelta/lingva-translate as a translation back-end? Web version seems to work better and more stable than SimplyTranslate.

**Comment by ManeraKai** [comment]
I should figure out what's wrong in my http requests, I don't wanna use another backend.

**Comment by ManeraKai** [comment]
There's just one thing that makes it ignore some requests before responding, it's the `X-Goog-BatchExecute-Bgr` http header. Also here they are having the same problem: https://github.com/Saravananslb/py-googletranslation/issues/27
