### ISSUE TITLE
Instances selection removed on latest version?

### ISSUE THREAD

**Issue by saebaryo-xyz** [ManeraKai/simplytranslate_mobile#229]
Hi,

I really would like to thank you for your amazingly hard work for making this app!
In the previous versions there was the possibility to add instances of Simplytranslate, but on the latest one I noticed that we can't anymore.

Are they any plans to bring them back in the futre maybe?

I am running my own instance of it on a small server and really wanted to use it and then advertise your app to some specialized local forum in which I'm sure they will be happy to see it, thanks!

**Comment by ManeraKai** [comment]
This app will stay as a frontend for Google Translate only, see [TranslateYou](https://github.com/Bnyro/TranslateYou) if you wanna use your instance.
