### ISSUE TITLE
Examples are not shown

### ISSUE THREAD

**Issue by danielleontiev** [ManeraKai/simplytranslate_mobile#232]
When using Google Translate on the web or in the official app it shows "examples" block for some words

<details>
<summary>screenshot of examples</summary>
<img src="https://github.com/ManeraKai/simplytranslate_mobile/assets/24596613/ffbd6ef5-1034-4630-b9a8-656ad08b8677" />
</details>

It would be great to show it in the application as well

**Comment by ManeraKai** [comment]
I don't think it's properly supported by google because, it's not shown much and only when you have both languages as the same language. Also, there's the examples after each definition which are more accurate for the context.
