### ISSUE TITLE
No "Customize Buttons" settings

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate_mobile#233]
In version 1.4.1 the "Customize Buttons" setting is not displayed.

**Comment by ManeraKai** [comment]
I removed it deliberately and also copy, paste, maximize icons.

**Comment by Valdnet** [comment]
> I removed it deliberately

Why? After all, this option allows you to configure the application according to the user.
> also copy, paste, maximize icons.

These options are also needed by the user.

@ManeraKai I have the impression that the application, instead of developing, is regressing in its functionality.

**Comment by ManeraKai** [comment]
> @ManeraKai I have the impression that the application, instead of developing, is regressing in its functionality

You can say so, I want to just focus on "translate using google translate" nothing else. I'm trying to keep it more robust since I don't have much time for fixing bugs and updating deprecated packages.

**Comment by Valdnet** [comment]
> I want to just focus on "translate using google translate" 

I'm behind that too :+1:.

More generally, the application is now more stable, but the buttons copy, paste, maximize icons are needed to handle text and in my opinion they should be restored.
