### ISSUE TITLE
Froze up immediately

### ISSUE THREAD

**Issue by DiagonalArg** [ManeraKai/simplytranslate_mobile#237]
I started the first time, tried to change the "from" languaguage (auto -> english), and while scrolling down the list of languages, the screen split in two: black on the left half, grey on the right.  "SimplyTranslate Mobile is on top with the 3 dot icon, and a green line, but below that is the split screen.  Shutdown of the app and restart doesn't help.  It's stuck in this state.  I am able to get into settings and choose that, but the only thing there is "Theme".  I'm also able to choose "About."  The stuck initial screen remains.

Pixel 7
GrapheneOS
Installed 1.4.3 from f-droid

**Comment by ManeraKai** [comment]
Weird, try to clear cache and storage of the app.

**Comment by DiagonalArg** [comment]
It's working now.  I'll report again if it glitches on me.
