### ISSUE TITLE
[suggest / ideia ]the app could have option to download languages for offline use (as the official one)

### ISSUE THREAD

**Issue by leao-nardo** [ManeraKai/simplytranslate_mobile#240]
with this function this app can completely replace the oficial one. if it had this i would be deleting the oficial and use only this

**Comment by ManeraKai** [comment]
I can't reverse engineer the mobile app to do this. I don't think this is possible.

**Comment by leao-nardo** [comment]
maybe in rooted phones one can download in the oficial and check in the files were and how its saved . then see if it can be copied and how can the local db/dictionary be acessed
