### ISSUE TITLE
Feature Request: Consider Adding Pinyin to Chinese Translation 

### ISSUE THREAD

**Issue by joseio** [ManeraKai/simplytranslate_mobile#243]
Similar to how Google Translate adds Pinyin to Chinese translation (see below image), perhaps you may consider adding the same functionality to the app as well. 

![IMG_20240309_221638](https://github.com/ManeraKai/simplytranslate_mobile/assets/25396169/4780a7de-f703-47b6-b7cc-94a4b431dbd8)

**Comment by ManeraKai** [comment]
You mean the spelling? We added that in simplytranslate. It won't be hard to add it here too in the mobile app.

**Comment by joseio** [comment]
Nice!!

**Comment by joseio** [comment]
One [unrelated] question for you: forgive my ignorance, but what makes this app a privacy-friendly frontend alternative to Google Translate? The rationale wasn't clear to me from the readme.

**Comment by ManeraKai** [comment]
It's that you don't need a google account nor any device identifier in order to send a request. The only thing that differs you from another mobile phone is your IP. There's no other fingerprint than this.

**Comment by joseio** [comment]
Thanks for the explanation! Very helpful
