### ISSUE TITLE
Hiding keyboard

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate_mobile#60]
Steps:

1. Launch the application.
2. Enter your text.
3. Hide the keyboard with the down arrow.
4. Tap on the text box.
5. Hide the keyboard again with the down arrow.

When you hide the keyboard again with the down arrow, the keyboard will hide and then pop out again, or behave in such a way that you have to tap the down arrow twice to hide the keyboard.

**Comment by Valdnet** [comment]
This happens when there is a "tear" in the text editor:

![obraz](https://user-images.githubusercontent.com/47037905/134037618-7425497a-5ead-44e9-b97e-8175e2cd1787.png)

**Comment by Valdnet** [comment]
The issue is still present in the latest test version.

Please reopen the issue.

**Comment by ManeraKai** [comment]
Testing it on a real device:

https://user-images.githubusercontent.com/40805353/134481058-35f59388-2f00-4c0e-b4b8-37d002376137.mp4

**Comment by Valdnet** [comment]
On my Android 10 device, it works like this:

1. I click on the text window.
2. Automatically ejects the keyboard.
3. I am writing the text.
4. I close the keyboard.
5. I click again in the text window.
6. Automatically slides out the keyboard and shows "tear".
7. I close the keyboard and here is the **difference**.

Behavior the Difference:
1. The "tear" disappears and the keyboard hides.
2. The keyboard restarts automatically without "tear".

**Comment by ManeraKai** [comment]
There are two requestFocus functions in the code. requestFocus means that the keyboard and the cursor will focus to an input, i.e the translation input, but those functions are just in the paste button file. Nothing else has that.
![image](https://user-images.githubusercontent.com/40805353/134487356-9bdd0390-713d-4efc-8615-d67a1d6f60c3.png)

**Comment by Valdnet** [comment]
Maybe there is an unexpected loop somewhere in the code that repeats the automatic eject of the keyboard. It looks as if editing the window has been repeated.

**Comment by ManeraKai** [comment]
Maybe setState. I'll see

**Comment by ManeraKai** [comment]
There is really nothing suspicious in the code. This issue will stay open though if anyone encountered the same problem. Maybe we can have more details about the devices having this issue.

**Comment by Valdnet** [comment]
I would check the editing of the window to see if there is anything suspicious there.

**Comment by Valdnet** [comment]
I noticed that in a different text editor (another application) First the keyboard hides and then after some time (about 1 second) the "tear" disappears. Maybe this will help you 😉.

**Comment by Valdnet** [comment]
It looks as if the disappearance of the "tear" starts editing the window again and the keyboard may pop up.

**Comment by ManeraKai** [comment]
I'll close this since it's mostly be a problem with Flutter not SimplyTranslate Mobile.
